### ISSUE TITLE
Correct login results in -> Connection to localhost closed.

### ISSUE THREAD

**Issue by theoneandonly-vector** [YunoHost-Apps/wetty_ynh#5] opened 2021-01-21 00:14 UTC
Correct login results in
->
Connection to localhost closed.

incorrect does not.

Hardware: VPS bought online
YunoHost version: 4.1.5 with all the latest updates
I have access to my server : Through SSH | through the webadmin
Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : no

**To Reproduce**
Install wetty through webpanel -> launch it and enter "yes" when asked for adding the host to the list of known hosts  then Enter the corrrect password.

**Expected behavior**
successful login

**Logs**
```
Could not create directory '/var/www/wetty/.ssh'.
The authenticity of host 'localhost (::1)' can't be established.
ECDSA key fingerprint is SHA256:***************************************.
Are you sure you want to continue connecting (yes/no)? yes
Failed to add the host to the list of known hosts (/var/www/wetty/.ssh/known_hosts).
Debian GNU/Linux 10
myusername@localhost's password: 
Permission denied, please try again.
myusername@localhost's password: 
```

**Comment by Salamandar** [comment] 2021-01-25 21:17
@theoneandonly-vector Can I get the log when the error appears ? What you pasted here shows "`Permission denied, please try again`", not "Connection to localhost closed".

You may see that kind of error : 

    bash: command not found: -p

If that's so, it's an error upstream, I tried to fix this but didn't help. We're gonna have to wait for the issue to be fixed upstream.

**Comment by theoneandonly-vector** [comment] 2021-01-25 22:11
![image](https://user-images.githubusercontent.com/10380051/105772453-78059e80-5f62-11eb-937a-2ebb70ca5791.png)

that's what it does. there's no output other than "Connection to localhost closed." after asking for my pasword -> me enterring the right password.

**Comment by theoneandonly-vector** [comment] 2021-01-28 21:31
I don't see any log-files inside "/var/log/wetty" is there anothe rplace I can look at?

**Comment by Salamandar** [comment] 2021-02-07 15:27
That should be fixed. Please upgrade (you should wait a few hours, because I just pushed it, you should see 2.0.3~ynh4 available).

**Comment by Salamandar** [comment] 2021-02-07 15:28
That should be fixed. Please upgrade (you should wait a few hours, because I just pushed it, you should see 2.0.3~ynh4 available).

Actually, the provided version is 2.0.2 because the author told to downgrade from 2.0.3. But yunohost is waiting for an update, so I just bumped the ynh revision.

**Comment by sharicov** [comment] 2021-02-09 13:49
Still impossible to use, disconnects upon successful login. May be related to the following issue: [https://forum.yunohost.org/t/ssh-disconnects-after-successful-login/256](url)

**Comment by Salamandar** [comment] 2021-02-14 13:38
@sharicov Please check that you can connect through SSH. If not, that probably is not related to Wetty. ;)

**Comment by sharicov** [comment] 2021-02-14 13:50
> @sharicov Please check that you can connect through SSH. If not, that probably is not related to Wetty. ;)
Thanks for response, Salamendar!
I can, but with different user (admin as by default in Yunohost). Wetty tries to connect me with Yunohost user (which is not a proper linux user and is blocked from SSH by Yunohost rules because of the security (it is described in the thread I mentioned above) .

**Comment by Salamandar** [comment] 2021-02-14 17:05
Right, okay, I understand what's happening now.

HTTP requests are sent with the user logged in Yunohost. Wetty now uses this "cookie" to force the user to log in.

You need either to log out of yunohost, or use private browsing, to log in ssh with wetty as, let's say, `admin`.

For me, that's a hard regression, I opened an issue upstream but no answer.

**Comment by sharicov** [comment] 2021-02-14 17:10
You are a genius! Works perfectly in incognito mode.
Thank you very much!

**Comment by sharicov** [comment] 2021-02-14 17:36
Is it possible to make wetty link to open in private tab automatically?

**Comment by Salamandar** [comment] 2021-02-15 08:33
> You are a genius! Works perfectly in incognito mode.
> Thank you very much!

I just had the issue myself :D I added this to the readme of the repository.

> Is it possible to make wetty link to open in private tab automatically?

You mean from the yunohost welcome page ? Hum… That could be interesting.

Also, SSOWat has a `auth_header` setting for each app. If I get it to be set at `false`, that should do the trick.

**Comment by Salamandar** [comment] 2021-05-19 17:29
That should now be fixed. An update (2.0.3~ynh5) should be available within hours/days.

**Closed** 2021-05-19 19:51 UTC
